# Access the id_github file from Secret Manager, and setup SSH
# blah blah blah blah
# blah blah blah
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:plosso/docker-compose-tutorial.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Build Docker image       
- name: 'gcr.io/cloud-builders/docker'
  id: "Build Docker File"
  args: ['build', '--no-cache', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/docker/docker:$SHORT_SHA', '.']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github/versions/latest
    env: 'SSH_KEY'

options:
 logging: CLOUD_LOGGING_ONLY
 